name = "frontend"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-07-31"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability.logs]
enabled = true

[placement]
mode = "smart"

[vars]
NODE_VERSION = "24.4.1"
ENVIRONMENT = "production"