name = "instafication-frontend"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-07-29"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[placement]
mode = "smart"

[vars]
NODE_VERSION="24.4.1"
ENVIRONMENT = "production"