name = "frontend"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-07-31"

routes = [
  { pattern = "instafication.shop", custom_domain = true }
]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability.logs]
enabled = true

[placement]
mode = "smart"

[vars]
NODE_VERSION = "24.4.1"
ENVIRONMENT = "production"

PUBLIC_POSTHOG_KEY="phc_HLDbWoUxDBzdI73yrjji2OWu6rLTzlVfThdLuh7wtYH"
PUBLIC_POSTHOG_HOST="https://eu.i.posthog.com"

PUBLIC_SUPABASE_URL="https://dkavcpubobbtovqtobkv.supabase.co"
PUBLIC_SUPABASE_ANON_KEY="sb_publishable_5-XfVjKYK6cWiV6s9K8M-g_kmze62xn"
DATABASE_URL="postgresql://postgres.dkavcpubobbtovqtobkv:hqD0xjNboPDubDqx@aws-0-eu-north-1.pooler.supabase.com:5432/postgres?sslmode=no-verify"
DB_PASSWORD="hqD0xjNboPDubDqx"

STRIPE_PUBLISHABLE_KEY=""
STRIPE_SECRET_KEY=""
STRIPE_WEBHOOK_SECRET=""

RESEND_API_KEY="re_KECmwWaz_MW4D5qz4BotMof1nugRXnmA7"